controllers/CommonController.php
<?php
/**
 * Created by PhpStorm.
 * User: Lenovo
 * Date: 15.06.2018
 * Time: 7:30
 */

namespace app\controllers;
use app\models\User;
use app\models\UserPhotos;
use Yii;
use yii\base\Controller;

class CommonController extends Controller
{
    public function actionPhoto(){
        $id = Yii::$app->request->get('id');
        $user_id = Yii::$app->request->get('user_id');

        $userPhotoModel = new  UserPhotos();
        $userModel = new User();

        $photo = $userPhotoModel->showPhoto($id);
        $userInfo = $userModel->getUserInfo($user_id);

        $current_profile_image = $userPhotoModel->getProfileImage($user_id);

        return $this->render('photo',[
            'photo' => $photo,
            'userInfo' => $userInfo,
            'current_profile_image' => $current_profile_image
        ]);
    }

}

controllers/OthersController.php
<?php

namespace app\controllers;

use app\models\CityList;
use app\models\Friend;
use app\models\ProfessionalSkills;
use app\models\SchoolList;
use app\models\UniversityList;
use app\models\User;
use app\models\UserCityRel;
use app\models\UserPhotos;
use app\models\UserRelations;
use app\models\UserRelationshipStatus;
use app\models\UserSchoolRel;
use app\models\UserUniversityRel;
use app\models\UserWorkPlaces;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class OthersController extends Controller
{


   /* protected  function beforeAction()
    {
        if(Yii::app()->user->isGuest)
            Yii::app()->user->loginRequired ();
        return true;
    }*/
    /**
     * {@inheritdoc}
     */
    /*public $allowedPages = [
        "login", "error",
        // all about USERS
        'users', 'deleteuser', 'viewuser', 'updateuser',
        //"signup",
    ];*/

    /*public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }*/


   /* public $allowedPages = [
        "login", "error",
        // all about USERS
        'users', 'deleteuser', 'viewuser', 'updateuser',
        //"signup",
    ];*/

    /*public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => $this->allowedPages,
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }*/

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    /*public function actionIndex()
    {
        return $this->render('index');
    }*/


    /*public function actionIndex()
    {
        $request = Yii::$app->request;
        $user_id = Yii::$app->user->identity['id'];
        $userName = Yii::$app->request->url;
        $userPhotoModel = new UserPhotos();
        $friendModel = new Friend();
        $userModel = new User();
        $workPlaceModel = new UserWorkPlaces();
        $userUniversityModel = new UserUniversityRel();

        if (Yii::$app->request->isPost){
            if ($request->post('UserPhotos')) {
                $userPhotoModel->images['profile_image'] = UploadedFile::getInstances($userPhotoModel, 'profile_image');
                $userPhotoModel->images['cover_image'] = UploadedFile::getInstances($userPhotoModel, 'cover_image');
                $userPhotoModel->images['other_image'] = UploadedFile::getInstances($userPhotoModel, 'other_image');
                $userPhotoModel->uploadFile($user_id);
            }
        }

        /*if($request->post('chooseProfileImage')){
            $imageId = $request->post('chooseProfileImage');
            $userPhotoModel->setProfileImage($imageId,$user_id);
        }*/

        /*$current_profile_image = $userPhotoModel->getProfileImage($user_id);
        $current_cover_image = $userPhotoModel->getCoverImage($user_id);
        $user_photos = $userPhotoModel->getUserPhotos($user_id);
        $all_photos = $userPhotoModel->getAllPhotos($user_id);
        $friends = $friendModel->getAllFriends($user_id);
        $all_users = $userModel->allUsers($user_id);
        $currentWorkPlace = $workPlaceModel->getCurrentWorkPlace($user_id);
        $allWorkPlaces = $workPlaceModel->allWorkPlaces($user_id);
        $allUniversities = $userUniversityModel->getAllUserUniversities($user_id);*/

        /*return $this->render('index',
        ['userPhotoModel' => $userPhotoModel,
         'current_profile_image' => $current_profile_image,
         'current_cover_image' => $current_cover_image,
         'user_photos' => $user_photos,
         'all_photos' => $all_photos,
         'friends' => $friends,
         'all_users' => $all_users,
         'currentWorkPlace' => $currentWorkPlace,
         'allWorkPlaces' => $allWorkPlaces,
         'allUniversities' => $allUniversities
        ]);
    }*/


    /*public function actionIndex(){
        $request = Yii::$app->request;
        $user_id = $request->get('id');
        //$userName = Yii::$app->request->url;
        $userPhotoModel = new UserPhotos();
        $friendModel = new Friend();
        $userModel = new User();
        $workPlaceModel = new UserWorkPlaces();
        $userUniversityModel = new UserUniversityRel();

        if (Yii::$app->request->isPost){
            if ($request->post('UserPhotos')) {
                $userPhotoModel->images['profile_image'] = UploadedFile::getInstances($userPhotoModel, 'profile_image');
                $userPhotoModel->images['cover_image'] = UploadedFile::getInstances($userPhotoModel, 'cover_image');
                $userPhotoModel->images['other_image'] = UploadedFile::getInstances($userPhotoModel, 'other_image');
                $userPhotoModel->uploadFile($user_id);
            }
        }

        if($request->post('chooseProfileImage')){
            $imageId = $request->post('chooseProfileImage');
            $userPhotoModel->setProfileImage($imageId,$user_id);
        }

        $current_profile_image = $userPhotoModel->getProfileImage($user_id);
        $current_cover_image = $userPhotoModel->getCoverImage($user_id);
        $user_photos = $userPhotoModel->getUserPhotos($user_id);
        $all_photos = $userPhotoModel->getAllPhotos($user_id);
        $friends = $friendModel->getAllFriends($user_id);
        $all_users = $userModel->allUsers($user_id);
        $currentWorkPlace = $workPlaceModel->getCurrentWorkPlace($user_id);
        $allWorkPlaces = $workPlaceModel->allWorkPlaces($user_id);
        $allUniversities = $userUniversityModel->getAllUserUniversities($user_id);

        return $this->render('index',
        ['userPhotoModel' => $userPhotoModel,
         'current_profile_image' => $current_profile_image,
         'current_cover_image' => $current_cover_image,
         'user_photos' => $user_photos,
         'all_photos' => $all_photos,
         'friends' => $friends,
         'all_users' => $all_users,
         'currentWorkPlace' => $currentWorkPlace,
         'allWorkPlaces' => $allWorkPlaces,
         'allUniversities' => $allUniversities
        ]);
    }*/


    public function actionProfile(){
        $logged_user_id = Yii::$app->user->identity['id'];
        $request = Yii::$app->request;
        $user_id = $request->get('id');
        $userName = $request->get('name');
        if($user_id) {
            $userPhotoModel = new UserPhotos();
            $friendModel = new Friend();
            $userModel = new User();
            $workPlaceModel = new UserWorkPlaces();
            $userUniversityModel = new UserUniversityRel();
            $current_profile_image = $userPhotoModel->getProfileImage($user_id);
            $current_cover_image = $userPhotoModel->getCoverImage($user_id);
            $user_photos = $userPhotoModel->getUserPhotos($user_id);
            $all_photos = $userPhotoModel->getAllPhotos($user_id);
            $friends = $friendModel->getAllFriends($user_id);
            $all_users = $userModel->allUsers($user_id);
            $user_info = $userModel->getUserInfo($user_id);
            $friendship_status = $friendModel->getFriendshipStatusForUser($logged_user_id,$user_id);
            if ($request->post('send_friend_request')) {
                $request_sent = $friendModel->sendFriendRequest($logged_user_id,$user_id);
                if($request_sent){
                    return $this->redirect(['profile/profile','id' => $user_id]);
                }
            }
            $allWorkPlaces = $workPlaceModel->allWorkPlaces($user_id);
            $allUniversities = $userUniversityModel->getAllUserUniversities($user_id);
            /*if($request->post('friend-request-confirm')){
                $friend_request_id = $request->post('friend-request-confirm');
                var_dump($friend_request_id);
                die;
            }*/
            return $this->render('profile',
                ['userPhotoModel' => $userPhotoModel,
                    'current_profile_image' => $current_profile_image,
                    'current_cover_image' => $current_cover_image,
                    'user_photos' => $user_photos,
                    'all_photos' => $all_photos,
                    'friends' => $friends,
                    'all_users' => $all_users,
                    'user_info'  => $user_info,
                    'friendship_status' => $friendship_status,
                    'allWorkPlaces' => $allWorkPlaces,
                    'allUniversities' => $allUniversities
                ]);
        }

        else {

            return false;
        }
    }


    public function actionPhotoAlbums(){
        $request = Yii::$app->request;
        $user_id = $request->get('id');
        if($user_id){

views/others/photo_albums.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
use yii\widgets\ActiveForm;
$this->title = 'My Yii Application';
?>
<div class="col-md-9">
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);?>
        <?php $_SESSION["csrf_token"] = md5(rand(0,10000000)).time();?>
        <input type="hidden" name="csrf_token" value="<?=
        htmlspecialchars($_SESSION["csrf_token"]);?>"
        />
        <div class=" row cover-image" style="height: 315px;border: 1px solid #d2d1d1;">
            <img style='width: 100%;max-height: 100%;' src="<?=(Yii::getAlias('@web').'/web/uploads/cover_image/'.($current_cover_image ? $current_cover_image : 'no-image.png'));?>" alt=""/>
            <div class="col-md-12" style="position: absolute;top: 130px;">
                <div class="col-md-3 profile-image">
                    <div style="height: 168px;width:168px;">
                        <img src="<?=(Yii::getAlias('@web').'/web/uploads/profile_image/'.($current_profile_image ? $current_profile_image : 'no-image.png'));?>" alt="" style="
                        max-height: 100%;width:100%;
                        border-radius: 5px 20px 5px;border: 2px solid white;
                            "/>
                    </div>
                </div>
                <div class="col-md-3 profile-name" style="padding-left: 0;">
                    <h1 style="color: white;">
                        <a style="text-decoration: none;color:white;"
                           href="<?= Url::toRoute(['others/profile','id'=> $user_info['id']]);?>"><?=$user_info['name'];?>
                        </a>
                    </h1>
                </div>
            </div>
        </div>
        <div class="row" style="padding-right: 0;padding-left: 0;margin-top: 30px;">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-file-image-o"></i> Photos
                </div>
                <div class="panel-body">
                    <?php
                        $byType = [];
                        foreach ($all_photos as $k => $data) {
                           $byType[$data['type']][] = $data;
                        }
                    ?>
                    <?php
                        foreach ($byType as $k => $images) {
                            foreach ($images as $image) {?>
                                <div class="col-md-3" style="padding-left: 0;padding-top: 10px;">
                                    <img style="width:100%;height: 206px;"
                                         src="<?=(Yii::getAlias('@web').'/web/uploads/'.$k.'/'.($image['hash_name'] ? $image['hash_name'] : 'no-image.png'));?>" alt=""/>
                                </div>
                            <?php } ?>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown link
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    <?php ActiveForm::end();?>
</div>

<style>
    #userphotos-cover_image {
        display: none;
    }

    #userphotos-profile_image{
        display: none;
    }


    #userphotos-other_image{
        display: none;
    }
</style>

views/others/profile.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'My Yii Application';
?>
<div class="col-md-9">
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);?>

   <!-- <?php /*$_SESSION["csrf_token"] = md5(rand(0,10000000)).time();*/?>
    <input type="hidden" name="csrf_token"
           value="<?/*=htmlspecialchars($_SESSION["csrf_token"]);*/?>"/>-->

    <div class="row cover-image" style="height: 315px;border: 1px solid #d2d1d1;">
            <a href="<?=Url::to(['common/photo','id'=> $current_cover_image['id'],
                'user_id'=> $user_info['id'] ]);?>">
                <img style='width: 100%;max-height: 100%;' src="<?=(Yii::getAlias('@web').'/web/uploads/cover_image/'.($current_cover_image['hash_name'] ? $current_cover_image['hash_name'] : 'no-image.png'));?>" alt=""/>
            </a>
            <div class="col-md-12" style="position: absolute;top: 130px;">
            <div class="col-md-3 profile-image">
                <div style="height: 168px;width:168px;">

                    <a href="<?=Url::to(['common/photo','id'=> $current_profile_image['id'],
                        'user_id'=> $user_info['id'] ]);?>">
                        <img src="<?=(Yii::getAlias('@web').'/web/uploads/profile_image/'.($current_profile_image['hash_name'] ? $current_profile_image['hash_name'] : 'no-image.png'));?>" alt="" style="
                            width: 168px;height: 168px;border-radius: 5px 20px 5px;border: 2px solid white;"/>
                    </a>
                </div>
            </div>
            <div class="col-md-3 profile-name" style="padding-left: 0;">
                <h1 style="color: white;">
                    <a style="text-decoration: none;color:white;"
                       href="<?= Url::toRoute(['others/profile','id'=> $user_info['id']]);?>"><?=$user_info['name'];?>
                    </a>
                </h1>
            </div>
            <div class="col-md-3" style="float: right;padding-top: 125px;text-align: right;">
                <input type="submit" name="send_friend_request"
                        class="btn btn-default" value="<?=$friendship_status?>"/>
            </div>
        </div>
    </div>


    <div class="row" style="padding-left: 0;padding-right: 0;margin-top: 15px;">
        <div class="col-md-5" style="padding-left: 0;">
            <div class="intro" >
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Intro
                    </div>
                    <div class="panel-body">
                        <?php foreach ($allWorkPlaces as $workPlace) {?>
                            <div class="col-md-12">
                                <i class="fa fa-briefcase"></i> <?=$workPlace['position'];?> at <?=$workPlace['company'];?>
                            </div>
                        <?php } ?>
                        <?php foreach ($allUniversities as $university) {?>
                            <div class="col-md-12">
                                <i class="fa fa-graduation-cap"></i> studied at <?=$university['name'];?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="friends">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-12">
                                <a style="" href="<?=Url::toRoute(['others/friends',
                                    'id'=> Yii::$app->request->get('id')]);?>">
                                    <i class="fa fa-users"></i> Friends
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <?php foreach ($friends as $friend) {?>
                            <div class="col-md-4">
                                <img src="<?=(Yii::getAlias('@web').'/web/uploads/profile_image/'.($friend['hash_name'] ? $friend['hash_name'] : 'no-image.png'));?>" alt=""
                                     style="border: 2px solid white;width: 100%;height: 100%;">
                                <?php if($friend['id'] == Yii::$app->user->identity['id']){?>
                                <a style="position: absolute;bottom: 0;left: 20px;color:white;" href="<?=Url::toRoute(['/'.Yii::$app->user->identity['name']]); ?>">
                                    <?=$friend['name'];?>
                                </a>
                                <?php } else { ?>
                                    <a style="position: absolute;bottom: 0;left: 20px;color:white;"
                                       href="<?=Url::toRoute(['others/profile','id' => $friend['id'] ]); ?>">
                                        <?=$friend['name'];?>
                                    </a>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="photos">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="<?= Url::toRoute(['others/photo-albums',
                                    'id'=> Yii::$app->request->get('id')]);?>"
                                    <i class="fa fa-file-image-o"></i> Photos
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <?php if(!empty($user_photos)) {
                            foreach ($user_photos as $k => $photo) { ?>
                                <div class="col-md-3">
                                    <img style="max-height: 100%;width: 100%;" src="<?=Yii::getAlias('@web').'/web/uploads/profile_image/'.$photo['hash_name'];?>" alt="">
                                </div>
                        <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-7" style="padding-right: 0;">
            <div class="user-timeLine">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row" style="height: 20px;">
                            <div class="col-md-3" style="height: 100%;padding-left:25px;border-right: 1px solid black;">
                                <?= $form->field($userPhotoModel, 'other_image', [
                                ])->fileInput()
                                    ->label('
                                    <div class="col-md-12"  style="cursor: pointer;padding-left:0;">
                                    <div class="col-md-6" style="padding-left: 0;padding-right: 0;text-align: center;">
                                        <i id="content-image-icon" style="font-size: 20px;opacity:0.9;cursor: pointer;" 
                                        class="fa fa-camera-retro"></i>
                                        </div>
                                        <div class="col-md-6" style="padding-left: 0;">
                                        <p>Photo</p>
                                        </div>
                                    </div>
                                 ');
                                ?>
                            </div>
                        </div>
                    </div>

                    <div class="panel-body">
                            <div class="col-md-2">

                                <a href="<?=Url::to(['common/photo','id'=> $current_profile_image['id'],
                                    'user_id'=> $user_info['id'] ]);?>">
                                <img class="image-circle" src="<?=(Yii::getAlias('@web').'/web/uploads/profile_image/'.($current_profile_image['hash_name'] ? $current_profile_image['hash_name'] : 'no-image.png'));?>" alt=""
                                     style="border-radius: 50%;width:40px;height:40px;"/>
                                </a>
                            </div>
                            <div class="col-md-10" style="padding-left: 0;">
                                <textarea style="resize:none;width: 100%;height: 90px;border: none;outline:none;"
                                          placeholder="What is in your mind?" name="" id=""></textarea>
                            </div>
                    </div>

                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-8" style="float: right;padding-right: 0;">

                                <div class="col-md-4" style="float: right;">
                                    <button class="btn btn-primary" style="float: right;">POST</button>
                                </div>

                                <div class="col-md-6" style="float: right;">
                                    <select class="form-control" name="" id="">
                                        <option value="">Only me</option>
                                        <option value="">Public</option>
                                        <option value="">Friends</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="user-content">
                <div class="post">
                    <div class="panel panel-default">
                        <div class="panel-heading">Content</div>
                        <div class="panel-body">
                            Content body
                        </div>
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-md-4" style="text-align: center;">
                                    <a href="#">
                                        <i class="fa fa-thumbs-o-up"></i> Like
                                    </a>

                                </div>
                                <div class="col-md-4" style="text-align: center;">
                                    <a href="#">
                                        <i class="fa fa-comment-o"></i> Comment
                                    </a>
                                </div>
                                <div class="col-md-4" style="text-align: center;">
                                    <a style="" href="#">
                                        <i class="fa fa-share-alt" aria-hidden="true"></i> Share
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <input type="submit" class="btn btn-success" value="Save"/>
    <?php ActiveForm::end();?>

</div>
<style>
    #userphotos-cover_image {
        display: none;
    }

    #userphotos-profile_image{
        display: none;
    }


    #userphotos-other_image{
        display: none;
    }

</style>
<style>
    .field-userphotos-cover_image{
        padding-left:10px;
        padding-top:5px;
        cursor: pointer;
    }

    #test:hover .field-userphotos-cover_image {
        background-color: black;
        transition: 0.3s;
        border-radius: 2px;
        border:1px solid white;
    }

    #test:hover .field-userphotos-cover_image {
        #hidden-cover-image-label-text {
            display: block;
        }
    }
</style>
<script>
    $(document).ready(function(){
        $("#profile_image_box").on('click',function(){
            $(".block-profile-image").show();
        });

        $("#close-profile-image-block").on("click",function(){
            $(".block-profile-image").hide();
        });
    });
</script>